sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - iojs
env:
  - secure: hsesfYnKYNcnSE5rSm6Fm7usVzqx2sAaPo9LhDKFwUKrR6a0/yHgTx/nMI65WEDhUyTBeoo+JlrsL42gVSxkD9YsUmb5c3lNnr2J8NU0LDqcfgH1qiH+zoZApNWgaFtDi+G3pyP1Cwa4g/SkX366VGQ4inoglnkeRknnonV2VIXQFew1Gl40klrlKp9aS7kgu7OUJ9sMXYvwLZVzdVlP+K05T1VjWnD5Yvk/goHJw8W6bGCFIMSlHm3iIYF6GdmeB/6zNJINNYr/R8VNum2J5U/VBxTVDiC1GZJmJ6Z/2PCSFEGpwJXnBR/pL/wu49a8KIirE4jg1+PfHp/knpN6FiZSFW0o4XCS2zQ5hjmHM7dHeYesmX/sjQ3shPlCpUNgO66Rr0kWOixte0O2GZzaDShEo9ff8bfUjAa78WInAVO3uniXnByYOptzZTHn3y6rqhIkWRjp2eS0AE4I7dODMFaySsc4PqUY0l0Hef/nE2eGpaPPmjt/3uiZtYVufoaBkvWi76qAqukoYg6OB2hha+Xk7CSC6ILSrF8FDMcRRJLUnTTWWV3Y8kEZydICT7CH9wCEgDMovVNJsVSOk5tBk9yiuYjakLV1LX3Bir0D6nHDqOT78IQxMiBdd0039U+vwZERtJuLGqeJhIl6lcEZcFEcsNVAlFQv8XX9uLTuruI=
after_success: npm run codeclimate
